# Generated by Django 6.1 on 2026-08-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CARD', 'Cardiology'), ('NEURO', 'Neurology'), ('ORTHO', 'Orthopedics'), ('PEDS', 'Pediatrics'), ('GEN', 'General Medicine'), ('DERM', 'Dermatology'), ('ENT', 'ENT'), ('GYNO', 'Gynecology')], default='GEN', max_length=10)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('admitted', models.BooleanField(default=False)),
                ('disease', models.CharField(blank=True, help_text='Diagnosis / reason for visit', max_length=200)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_on'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('CONF', 'Confirmed'), ('DONE', 'Completed'), ('CANC', 'Cancelled')], default='PEND', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.patient')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
