# Generated by Django 5.2.17 on 2026-08-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('APPT_NEW', 'New Appointment'), ('APPT_STATUS', 'Appointment Status Changed'), ('PATIENT_ADMIT', 'Patient Admitted'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, help_text='Optional URL name to redirect to', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
